# Generated by Django 4.2 on 2025-05-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Cliente'), ('ADMIN', 'Administrador')], default='CLIENT', max_length=10, verbose_name='Rol'),
        ),
    ]
