# Generated by Django 4.2 on 2025-05-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cedula',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Cédula'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
