INSERT INTO products_pizza (name, description, size, price, image) VALUES
('Pizza Greta', 'Salsa de tomate natural, mozzarella y albahaca fresca', 'Pequeña', 12.5, 'https://i.postimg.cc/T2sCVJhc/pexels-enginakyurt-1437810.webp'),
('Pizza Ludewico', 'Pepperoni ahumado alemán, queso gouda y cebolla caramelizada', 'Grande', 14.75, 'https://i.postimg.cc/N0zhSm5Q/pexels-asya-vlasova-228168-3229356.jpg'),
('Pizza Bigote', 'Especialidad de la casa con salchicha bratwurst y mostaza artesanal', 'Grande', 15.2, 'https://i.postimg.cc/qRPPMrsY/pexels-athena-2180875.jpg'),
('Pizza Schwarzwald', 'Jamón de la Selva Negra, champiñones y queso emmental', 'Grande', 13.9, 'https://i.postimg.cc/Mpz8QzCJ/pexels-bananamade-2762942.jpg'),
('Pizza Otto', 'Salsa de crema, speck alemán y rúcula', 'Mediana', 14.3, 'https://i.postimg.cc/LsXKxN4y/pexels-beqa-tefnadze-264627-803290.jpg'),
('Pizza Bavaria', 'Chucrut, salchicha weisswurst y queso alpino', 'Grande', 15, 'https://i.postimg.cc/1tVxQXqw/pexels-cantuariabruno-774487.jpg'),
('Pizza Hans', 'Pollo asado, pimientos y salsa de cerveza oscura', 'Pequeña', 13.5, 'https://i.postimg.cc/1XDL8dMz/pexels-catscoming-365459.jpg'),
('Pizza Käse', 'Mezcla de quesos alemanes: emmental, gouda y tilsit', 'Grande', 14, 'https://i.postimg.cc/SQ801Xqp/pexels-catscoming-367915.jpg'),
('Pizza Sauer', 'Salsa de tomate, salami picante y pepinillos', 'Pequeña', 12.8, 'https://i.postimg.cc/FsQMM9sk/pexels-cottonbro-3944308.jpg'),
('Pizza Berliner', 'Carne molida especiada, cebolla y salsa curry', 'Pequeña', 13.2, 'https://i.postimg.cc/cJjjXWbH/pexels-cottonbro-4004418.jpg'),
('Pizza Fritz', 'Salmón ahumado, eneldo y crema fresca', 'Grande', 16, 'https://i.postimg.cc/GhJWrZH7/pexels-creative-vix-375467.jpg'),
('Pizza Heidi', 'Espinacas, queso de cabra y nueces', 'Mediana', 14.5, 'https://i.postimg.cc/524Ztnzx/pexels-edwardeyer-1049620.jpg'),
('Pizza Wolfgang', 'Chorizo alemán, pimientos asados y mozzarella', 'Grande', 13.7, 'https://i.postimg.cc/PqN9WJK9/pexels-edwardeyer-1049626.jpg'),
('Pizza Edelweiss', 'Salsa blanca, papas asadas y romero', 'Grande', 12.9, 'https://i.postimg.cc/1tqdddkK/pexels-enginakyurt-1435900.jpg'),
('Pizza König', 'Jamón serrano, higos y queso azul', 'Mediana', 15.5, 'https://i.postimg.cc/3NQqQB7Q/pexels-enginakyurt-1435903.jpg'),
('Pizza Rind', 'Carne de res desmechada, cebolla y salsa barbacoa', 'Grande', 14.8, 'https://i.postimg.cc/BQszhMMx/pexels-enginakyurt-1435907.jpg'),
('Pizza Liesel', 'Calabacín, ricotta y aceite de trufa', 'Mediana', 15.3, 'https://i.postimg.cc/jS3kSKKX/pexels-enginakyurt-1437810.jpg'),
('Pizza Brat', 'Salchicha bratwurst, chucrut y mostaza Dijon', 'Grande', 14.2, 'https://i.postimg.cc/Hn0hYysc/pexels-enginakyurt-1458426.jpg'),
('Pizza Dunkel', 'Salsa de cerveza negra, queso ahumado y tocino', 'Pequeña', 14.9, 'https://i.postimg.cc/15Hjbwjb/pexels-enginakyurt-1552635.jpg'),
('Pizza Alpen', 'Queso raclette, jamón crudo y cebollino', 'Grande', 15.7, 'https://i.postimg.cc/y88bKWqx/pexels-enginakyurt-2260555.jpg'),
('Pizza Müller', 'Salsa de tomate, salchicha knackwurst y pimientos', 'Pequeña', 13.4, 'https://i.postimg.cc/mk4m5gNb/pexels-enginakyurt-2271194.jpg'),
('Pizza Hefe', 'Levadura de cerveza en la masa, queso y orégano', 'Grande', 12.6, 'https://i.postimg.cc/T1ctMvCn/pexels-enginakyurt-2619967.jpg'),
('Pizza Spätzle', 'Salsa cremosa, queso rallado y trozos de spätzle', 'Grande', 14.1, 'https://i.postimg.cc/8kdKrLNs/pexels-enginakyurt-2619970.jpg'),
('Pizza Jäger', 'Champiñones salteados, carne de caza y hierbas', 'Grande', 15, 'https://i.postimg.cc/nL6RqkX9/pexels-grizzlybear-1166120.jpg'),
('Pizza Rhein', 'Salmón, espárragos y salsa holandesa', 'Pequeña', 16.2, 'https://i.postimg.cc/kXnjNDgs/pexels-horizon-content-2100060-3826016.jpg'),
('Pizza Brezel', 'Masa con sal gruesa, queso y mantequilla de ajo', 'Grande', 13, 'https://i.postimg.cc/ZRtHW5Qr/pexels-horizon-content-2100060-3915857.jpg'),
('Pizza Fritzchen', 'Atún, aceitunas negras y cebolla roja', 'Pequeña', 13.8, 'https://i.postimg.cc/VkvDTTMb/pexels-igrejapreta-2608049.jpg'),
('Pizza Elsa', 'Salsa de tomate, mozzarella y jamón ahumado', 'Grande', 12.7, 'https://i.postimg.cc/02cVVx6s/pexels-ikeen-james-1194926-2274787.jpg'),
('Pizza Schnitzel', 'Milanesa de pollo, tomate y queso fundido', 'Pequeña', 14.4, 'https://i.postimg.cc/GtzxgJmQ/pexels-jeshoots-3588.jpg'),
('Pizza Apfel', 'Manzanas asadas, queso brie y nueces', 'Grande', 15.1, 'https://i.postimg.cc/mrFVZHmL/pexels-jeshoots-3644.jpg'),
('Pizza Wurst', 'Variedad de salchichas alemanas y queso', 'Grande', 14.6, 'https://i.postimg.cc/sx3JJ0sx/pexels-kei-photo-1420806-2741457.jpg'),
('Pizza Rotkohl', 'Repollo morado, queso crema y speck', 'Pequeña', 13.9, 'https://i.postimg.cc/YCvz8FK6/pexels-kevinbidwell-1788852.jpg'),
('Pizza Stein', 'Salsa picante, chorizo y jalapeños', 'Grande', 13.3, 'https://i.postimg.cc/X778GhsD/pexels-littlesoad-2909821.jpg'),
('Pizza Guten', 'Salsa de tomate, queso y albóndigas alemanas', 'Mediana', 14, 'https://i.postimg.cc/J7Qxhm5k/pexels-littlesoad-2918521.jpg'),
('Pizza Märzen', 'Salsa de cerveza Märzen, queso y cebolla', 'Mediana', 14.7, 'https://i.postimg.cc/nzJKHws2/pexels-miyatavictor-3682837.jpg'),
('Pizza Kürbis', 'Calabaza asada, queso de cabra y salvia', 'Mediana', 15.4, 'https://i.postimg.cc/cCDfBxFk/pexels-muffin-1653877.jpg'),
('Pizza Zwiebel', 'Cebolla caramelizada, queso azul y nueces', 'Mediana', 14.2, 'https://i.postimg.cc/PrxWrDqg/pexels-natasha-filippovskaya-2203043-4394612.jpg'),
('Pizza Huhn', 'Pollo marinado, maíz y crema agria', 'Pequeña', 13.6, 'https://i.postimg.cc/pd8YMtdy/pexels-pablo-macedo-287472-845798.jpg'),
('Pizza Senf', 'Mostaza artesanal, salchicha y queso', 'Mediana', 14.3, 'https://i.postimg.cc/3r9jT13j/pexels-pablo-macedo-287472-845812.jpg'),
('Pizza Pilsner', 'Salsa de cerveza Pilsner, queso y tocino', 'Grande', 14.8, 'https://i.postimg.cc/xT4KkdJc/pexels-pixabay-162744.jpg'),
('Pizza Kräuter', 'Hierbas frescas, tomate cherry y mozzarella', 'Mediana', 12.9, 'https://i.postimg.cc/kgRWWdKw/pexels-pixabay-208537.jpg'),
('Pizza Rüben', 'Remolacha asada, queso feta y rúcula', 'Grande', 14.5, 'https://i.postimg.cc/hvGdvFKL/pexels-pixabay-262977.jpg'),
('Pizza Bock', 'Salsa de cerveza Bock, carne y queso ahumado', 'Grande', 15, 'https://i.postimg.cc/5twvkqPC/pexels-pixabay-263041.jpg'),
('Pizza Gold', 'Salsa de miel, queso gorgonzola y peras', 'Mediana', 15.6, 'https://i.postimg.cc/Pr9wXF9D/pexels-pixabay-280453.jpg'),
('Pizza Pfeffer', 'Pimienta negra, salami y queso', 'Grande', 13.2, 'https://i.postimg.cc/B64DWLyw/pexels-polina-tankilevitch-4109077.jpg'),
('Pizza Lauch', 'Puerros salteados, crema y queso emmental', 'Grande', 14.1, 'https://i.postimg.cc/jjQwhq56/pexels-polina-tankilevitch-4109083.jpg'),
('Pizza Speck', 'Speck alemán, champiñones y mozzarella', 'Pequeña', 14.7, 'https://i.postimg.cc/GmDsHxn5/pexels-polina-tankilevitch-4109111.jpg'),
('Pizza Tomaten', 'Tomates frescos, albahaca y queso', 'Grande', 12.8, 'https://i.postimg.cc/MG8fRfWK/pexels-polina-tankilevitch-4109128.jpg'),
('Pizza Knoblauch', 'Ajo asado, queso y perejil', 'Pequeña', 13, 'https://i.postimg.cc/qRJtDfhP/pexels-renestrgar-10406184.jpg'),
('Pizza Käsekuchen', 'Salsa blanca, queso crema y cebollino', 'Pequeña', 14.4, 'https://i.postimg.cc/SsgnwZcJ/pexels-renestrgar-10836977.jpg'),
('Pizza Schinken', 'Jamón ahumado, piña y queso', 'Grande', 13.5, 'https://i.postimg.cc/Dy9Sk44d/pexels-renestrgar-13814644.jpg'),
('Pizza Spargel', 'Espárragos blancos, crema y queso', 'Pequeña', 14.9, 'https://i.postimg.cc/MH4vGvPw/pexels-roman-odintsov-4553111.jpg'),
('Pizza Pilz', 'Variedad de hongos, queso y trufa', 'Grande', 15.3, 'https://i.postimg.cc/J7dyx21F/pexels-roman-odintsov-4553123.jpg'),
('Pizza Currywurst', 'Salchicha currywurst, salsa picante y queso', 'Grande', 14, 'https://i.postimg.cc/pXhm6JrL/pexels-roman-odintsov-4553127.jpg'),
('Pizza Rahm', 'Salsa de crema, espinacas y queso', 'Mediana', 14.6, 'https://i.postimg.cc/dVGLqQ8M/pexels-roman-odintsov-5903101.jpg'),
('Pizza Frisch', 'Vegetales frescos, mozzarella y aceite', 'Mediana', 13.1, 'https://i.postimg.cc/R0RhHPsX/pexels-shamia-casiano-183672-874500.jpg'),
('Pizza Bayern', 'Salchicha bávara, queso y cebolla', 'Pequeña', 14.2, 'https://i.postimg.cc/DzFmmVgS/pexels-sydney-troxell-223521-708587.jpg'),
('Pizza Dunkelweizen', 'Salsa de cerveza de trigo, queso y tocino', 'Mediana', 14.8, 'https://i.postimg.cc/5yH2DfxR/pexels-taryn-elliott-7172067.jpg'),
('Pizza Kartoffel', 'Papas asadas, queso y romero', 'Mediana', 13.4, 'https://i.postimg.cc/Y2V9YLRK/pexels-vince-2147491.jpg'),
('Pizza Leber', 'Hígado encebollado, queso y salsa', 'Pequeña', 15, 'https://i.postimg.cc/bJVv6Zjn/pexels-vince-2233348.jpg'),
('Pizza Kohl', 'Repollo salteado, queso y speck', 'Grande', 14.3, 'https://i.postimg.cc/28Z5wj9q/pexels-vince-2295285.jpg'),
('Pizza Zitrone', 'Limón, queso ricotta y rúcula', 'Mediana', 14.7, 'https://i.postimg.cc/TYV61KHc/pexels-ahmad-nawawi-285301-2714722.jpg'),
('Pizza Pfefferspeck', 'Speck picante, queso y pimientos', 'Mediana', 14.1, 'https://i.postimg.cc/N0zhSm5Q/pexels-asya-vlasova-228168-3229356.jpg'),
('Pizza Helles', 'Salsa de cerveza Helles, queso y hierbas', 'Grande', 14.5, 'https://i.postimg.cc/qRPPMrsY/pexels-athena-2180875.jpg'),
('Pizza Gurken', 'Pepinillos, queso crema y salmón', 'Mediana', 15.2, 'https://i.postimg.cc/Mpz8QzCJ/pexels-bananamade-2762942.jpg'),
('Pizza Sauerbraten', 'Carne marinada, queso y cebolla', 'Mediana', 14.9, 'https://i.postimg.cc/LsXKxN4y/pexels-beqa-tefnadze-264627-803290.jpg'),
('Pizza Rote', 'Pimientos rojos asados, queso y albahaca', 'Grande', 13.6, 'https://i.postimg.cc/1tVxQXqw/pexels-cantuariabruno-774487.jpg'),
('Pizza Grün', 'Espinacas, queso feta y nueces', 'Mediana', 14.4, 'https://i.postimg.cc/1XDL8dMz/pexels-catscoming-365459.jpg'),
('Pizza Weiss', 'Salsa blanca, salchicha y queso', 'Pequeña', 14, 'https://i.postimg.cc/SQ801Xqp/pexels-catscoming-367915.jpg'),
('Pizza Schwarzer', 'Salsa de tinta, queso y mariscos', 'Mediana', 15.8, 'https://i.postimg.cc/FsQMM9sk/pexels-cottonbro-3944308.jpg'),
('Pizza Honig', 'Miel, queso brie y almendras', 'Mediana', 15.4, 'https://i.postimg.cc/cJjjXWbH/pexels-cottonbro-4004418.jpg'),
('Pizza Kräuterbutter', 'Mantequilla de hierbas, queso y ajo', 'Grande', 13.7, 'https://i.postimg.cc/GhJWrZH7/pexels-creative-vix-375467.jpg'),
('Pizza Rinder', 'Carne de res, queso y cebolla', 'Grande', 14.6, 'https://i.postimg.cc/524Ztnzx/pexels-edwardeyer-1049620.jpg'),
('Pizza Gemüse', 'Vegetales asados, queso y orégano', 'Pequeña', 13.2, 'https://i.postimg.cc/PqN9WJK9/pexels-edwardeyer-1049626.jpg'),
('Pizza Lachs', 'Salmón ahumado, queso crema y eneldo', 'Pequeña', 15.9, 'https://i.postimg.cc/1tqdddkK/pexels-enginakyurt-1435900.jpg'),
('Pizza Eier', 'Huevos revueltos, queso y tocino', 'Grande', 14.1, 'https://i.postimg.cc/3NQqQB7Q/pexels-enginakyurt-1435903.jpg'),
('Pizza Käsekrainer', 'Salchicha con queso, mostaza y cebolla', 'Pequeña', 14.5, 'https://i.postimg.cc/BQszhMMx/pexels-enginakyurt-1435907.jpg'),
('Pizza Ziegen', 'Queso de cabra, higos y miel', 'Grande', 15.3, 'https://i.postimg.cc/jS3kSKKX/pexels-enginakyurt-1437810.jpg'),
('Pizza Trüffel', 'Aceite de trufa, queso y champiñones', 'Pequeña', 16, 'https://i.postimg.cc/Hn0hYysc/pexels-enginakyurt-1458426.jpg'),
('Pizza Mais', 'Maíz, queso y pimientos', 'Grande', 13.4, 'https://i.postimg.cc/15Hjbwjb/pexels-enginakyurt-1552635.jpg'),
('Pizza Rucola', 'Rúcula fresca, queso y jamón crudo', 'Grande', 14.7, 'https://i.postimg.cc/y88bKWqx/pexels-enginakyurt-2260555.jpg'),
('Pizza Senfkorn', 'Mostaza en grano, queso y salchicha', 'Mediana', 14.2, 'https://i.postimg.cc/mk4m5gNb/pexels-enginakyurt-2271194.jpg'),
('Pizza Fenchel', 'Hinojo asado, queso y limón', 'Mediana', 14.8, 'https://i.postimg.cc/GtzxgJmQ/pexels-jeshoots-3588.jpg'),
('Pizza Kümmel', 'Comino, queso y speck', 'Grande', 14, 'https://i.postimg.cc/mrFVZHmL/pexels-jeshoots-3644.jpg'),
('Pizza Oliven', 'Aceitunas, queso y tomate', 'Mediana', 13.5, 'https://i.postimg.cc/sx3JJ0sx/pexels-kei-photo-1420806-2741457.jpg'),
('Pizza Paprika', 'Pimientos variados, queso y salami', 'Mediana', 14.3, 'https://i.postimg.cc/YCvz8FK6/pexels-kevinbidwell-1788852.jpg'),
('Pizza Butter', 'Mantequilla, queso y hierbas', 'Grande', 13, 'https://i.postimg.cc/X778GhsD/pexels-littlesoad-2909821.jpg'),
('Pizza Radieschen', 'Rábanos, queso crema y rúcula', 'Grande', 14.6, 'https://i.postimg.cc/J7Qxhm5k/pexels-littlesoad-2918521.jpg'),
('Pizza Schaf', 'Queso de oveja, tomate y albahaca', 'Mediana', 14.9, 'https://i.postimg.cc/nzJKHws2/pexels-miyatavictor-3682837.jpg'),
('Pizza Fisch', 'Pescado blanco, queso y limón', 'Grande', 15.5, 'https://i.postimg.cc/cCDfBxFk/pexels-muffin-1653877.jpg'),
('Pizza Käsefondue', 'Salsa de queso fundido y pan', 'Grande', 14.2, 'https://i.postimg.cc/PrxWrDqg/pexels-natasha-filippovskaya-2203043-4394612.jpg'),
('Pizza Salz', 'Sal gruesa, queso y romero', 'Mediana', 13.8, 'https://i.postimg.cc/pd8YMtdy/pexels-pablo-macedo-287472-845798.jpg'),
('Pizza Kräuteröl', 'Aceite de hierbas, queso y tomate', 'Grande', 14.4, 'https://i.postimg.cc/3r9jT13j/pexels-pablo-macedo-287472-845812.jpg'),
('Pizza Zuckerrüben', 'Remolacha dulce, queso y nueces', 'Mediana', 14.7, 'https://i.postimg.cc/xT4KkdJc/pexels-pixabay-162744.jpg'),
('Pizza Knobli', 'Ajo fresco, queso y perejil', 'Grande', 13.3, 'https://i.postimg.cc/kgRWWdKw/pexels-pixabay-208537.jpg'),
('Pizza Schmalz', 'Grasa de cerdo, queso y cebolla', 'Grande', 14.5, 'https://i.postimg.cc/hvGdvFKL/pexels-pixabay-262977.jpg'),
('Pizza Eintopf', 'Guiso de vegetales, queso y pan', 'Mediana', 14, 'https://i.postimg.cc/5twvkqPC/pexels-pixabay-263041.jpg'),
('Pizza Finale', 'Mezcla de todos los ingredientes estrella', 'Mediana', 15, 'https://i.postimg.cc/Pr9wXF9D/pexels-pixabay-280453.jpg'),
('Pizza Extra Käse', 'Extra queso mozzarella y gouda', 'Grande', 14.8, 'https://i.postimg.cc/B64DWLyw/pexels-polina-tankilevitch-4109077.jpg');