INSERT INTO pizzas (name, description, size, price, image) VALUES
('Pizza Greta', 'Salsa de tomate natural, mozzarella y albahaca fresca', 'Pequeña', 12.5, NULL),
('Pizza Ludewico', 'Pepperoni ahumado alemán, queso gouda y cebolla caramelizada', 'Grande', 14.75, NULL),
('Pizza Bigote', 'Especialidad de la casa con salchicha bratwurst y mostaza artesanal', 'Grande', 15.2, NULL),
('Pizza Schwarzwald', 'Jamón de la Selva Negra, champiñones y queso emmental', 'Grande', 13.9, NULL),
('Pizza Otto', 'Salsa de crema, speck alemán y rúcula', 'Mediana', 14.3, NULL),
('Pizza Bavaria', 'Chucrut, salchicha weisswurst y queso alpino', 'Grande', 15, NULL),
('Pizza Hans', 'Pollo asado, pimientos y salsa de cerveza oscura', 'Pequeña', 13.5, NULL),
('Pizza Käse', 'Mezcla de quesos alemanes: emmental, gouda y tilsit', 'Grande', 14, NULL),
('Pizza Sauer', 'Salsa de tomate, salami picante y pepinillos', 'Pequeña', 12.8, NULL),
('Pizza Berliner', 'Carne molida especiada, cebolla y salsa curry', 'Pequeña', 13.2, NULL),
('Pizza Fritz', 'Salmón ahumado, eneldo y crema fresca', 'Grande', 16, NULL),
('Pizza Heidi', 'Espinacas, queso de cabra y nueces', 'Mediana', 14.5, NULL),
('Pizza Wolfgang', 'Chorizo alemán, pimientos asados y mozzarella', 'Grande', 13.7, NULL),
('Pizza Edelweiss', 'Salsa blanca, papas asadas y romero', 'Grande', 12.9, NULL),
('Pizza König', 'Jamón serrano, higos y queso azul', 'Mediana', 15.5, NULL),
('Pizza Rind', 'Carne de res desmechada, cebolla y salsa barbacoa', 'Grande', 14.8, NULL),
('Pizza Liesel', 'Calabacín, ricotta y aceite de trufa', 'Mediana', 15.3, NULL),
('Pizza Brat', 'Salchicha bratwurst, chucrut y mostaza Dijon', 'Grande', 14.2, NULL),
('Pizza Dunkel', 'Salsa de cerveza negra, queso ahumado y tocino', 'Pequeña', 14.9, NULL),
('Pizza Alpen', 'Queso raclette, jamón crudo y cebollino', 'Grande', 15.7, NULL),
('Pizza Müller', 'Salsa de tomate, salchicha knackwurst y pimientos', 'Pequeña', 13.4, NULL),
('Pizza Hefe', 'Levadura de cerveza en la masa, queso y orégano', 'Grande', 12.6, NULL),
('Pizza Spätzle', 'Salsa cremosa, queso rallado y trozos de spätzle', 'Grande', 14.1, NULL),
('Pizza Jäger', 'Champiñones salteados, carne de caza y hierbas', 'Grande', 15, NULL),
('Pizza Rhein', 'Salmón, espárragos y salsa holandesa', 'Pequeña', 16.2, NULL),
('Pizza Brezel', 'Masa con sal gruesa, queso y mantequilla de ajo', 'Grande', 13, NULL),
('Pizza Fritzchen', 'Atún, aceitunas negras y cebolla roja', 'Pequeña', 13.8, NULL),
('Pizza Elsa', 'Salsa de tomate, mozzarella y jamón ahumado', 'Grande', 12.7, NULL),
('Pizza Schnitzel', 'Milanesa de pollo, tomate y queso fundido', 'Pequeña', 14.4, NULL),
('Pizza Apfel', 'Manzanas asadas, queso brie y nueces', 'Grande', 15.1, NULL),
('Pizza Wurst', 'Variedad de salchichas alemanas y queso', 'Grande', 14.6, NULL),
('Pizza Rotkohl', 'Repollo morado, queso crema y speck', 'Pequeña', 13.9, NULL),
('Pizza Stein', 'Salsa picante, chorizo y jalapeños', 'Grande', 13.3, NULL),
('Pizza Guten', 'Salsa de tomate, queso y albóndigas alemanas', 'Mediana', 14, NULL),
('Pizza Märzen', 'Salsa de cerveza Märzen, queso y cebolla', 'Mediana', 14.7, NULL),
('Pizza Kürbis', 'Calabaza asada, queso de cabra y salvia', 'Mediana', 15.4, NULL),
('Pizza Zwiebel', 'Cebolla caramelizada, queso azul y nueces', 'Mediana', 14.2, NULL),
('Pizza Huhn', 'Pollo marinado, maíz y crema agria', 'Pequeña', 13.6, NULL),
('Pizza Senf', 'Mostaza artesanal, salchicha y queso', 'Mediana', 14.3, NULL),
('Pizza Pilsner', 'Salsa de cerveza Pilsner, queso y tocino', 'Grande', 14.8, NULL),
('Pizza Kräuter', 'Hierbas frescas, tomate cherry y mozzarella', 'Mediana', 12.9, NULL),
('Pizza Rüben', 'Remolacha asada, queso feta y rúcula', 'Grande', 14.5, NULL),
('Pizza Bock', 'Salsa de cerveza Bock, carne y queso ahumado', 'Grande', 15, NULL),
('Pizza Gold', 'Salsa de miel, queso gorgonzola y peras', 'Mediana', 15.6, NULL),
('Pizza Pfeffer', 'Pimienta negra, salami y queso', 'Grande', 13.2, NULL),
('Pizza Lauch', 'Puerros salteados, crema y queso emmental', 'Grande', 14.1, NULL),
('Pizza Speck', 'Speck alemán, champiñones y mozzarella', 'Pequeña', 14.7, NULL),
('Pizza Tomaten', 'Tomates frescos, albahaca y queso', 'Grande', 12.8, NULL),
('Pizza Knoblauch', 'Ajo asado, queso y perejil', 'Pequeña', 13, NULL),
('Pizza Käsekuchen', 'Salsa blanca, queso crema y cebollino', 'Pequeña', 14.4, NULL),
('Pizza Schinken', 'Jamón ahumado, piña y queso', 'Grande', 13.5, NULL),
('Pizza Spargel', 'Espárragos blancos, crema y queso', 'Pequeña', 14.9, NULL),
('Pizza Pilz', 'Variedad de hongos, queso y trufa', 'Grande', 15.3, NULL),
('Pizza Currywurst', 'Salchicha currywurst, salsa picante y queso', 'Grande', 14, NULL),
('Pizza Rahm', 'Salsa de crema, espinacas y queso', 'Mediana', 14.6, NULL),
('Pizza Frisch', 'Vegetales frescos, mozzarella y aceite', 'Mediana', 13.1, NULL),
('Pizza Bayern', 'Salchicha bávara, queso y cebolla', 'Pequeña', 14.2, NULL),
('Pizza Dunkelweizen', 'Salsa de cerveza de trigo, queso y tocino', 'Mediana', 14.8, NULL),
('Pizza Kartoffel', 'Papas asadas, queso y romero', 'Mediana', 13.4, NULL),
('Pizza Leber', 'Hígado encebollado, queso y salsa', 'Pequeña', 15, NULL),
('Pizza Kohl', 'Repollo salteado, queso y speck', 'Grande', 14.3, NULL),
('Pizza Zitrone', 'Limón, queso ricotta y rúcula', 'Mediana', 14.7, NULL),
('Pizza Pfefferspeck', 'Speck picante, queso y pimientos', 'Mediana', 14.1, NULL),
('Pizza Helles', 'Salsa de cerveza Helles, queso y hierbas', 'Grande', 14.5, NULL),
('Pizza Gurken', 'Pepinillos, queso crema y salmón', 'Mediana', 15.2, NULL),
('Pizza Sauerbraten', 'Carne marinada, queso y cebolla', 'Mediana', 14.9, NULL),
('Pizza Rote', 'Pimientos rojos asados, queso y albahaca', 'Grande', 13.6, NULL),
('Pizza Grün', 'Espinacas, queso feta y nueces', 'Mediana', 14.4, NULL),
('Pizza Weiss', 'Salsa blanca, salchicha y queso', 'Pequeña', 14, NULL),
('Pizza Schwarzer', 'Salsa de tinta, queso y mariscos', 'Mediana', 15.8, NULL),
('Pizza Honig', 'Miel, queso brie y almendras', 'Mediana', 15.4, NULL),
('Pizza Kräuterbutter', 'Mantequilla de hierbas, queso y ajo', 'Grande', 13.7, NULL),
('Pizza Rinder', 'Carne de res, queso y cebolla', 'Grande', 14.6, NULL),
('Pizza Gemüse', 'Vegetales asados, queso y orégano', 'Pequeña', 13.2, NULL),
('Pizza Lachs', 'Salmón ahumado, queso crema y eneldo', 'Pequeña', 15.9, NULL),
('Pizza Eier', 'Huevos revueltos, queso y tocino', 'Grande', 14.1, NULL),
('Pizza Käsekrainer', 'Salchicha con queso, mostaza y cebolla', 'Pequeña', 14.5, NULL),
('Pizza Ziegen', 'Queso de cabra, higos y miel', 'Grande', 15.3, NULL),
('Pizza Trüffel', 'Aceite de trufa, queso y champiñones', 'Pequeña', 16, NULL),
('Pizza Mais', 'Maíz, queso y pimientos', 'Grande', 13.4, NULL),
('Pizza Rucola', 'Rúcula fresca, queso y jamón crudo', 'Grande', 14.7, NULL),
('Pizza Senfkorn', 'Mostaza en grano, queso y salchicha', 'Mediana', 14.2, NULL),
('Pizza Fenchel', 'Hinojo asado, queso y limón', 'Mediana', 14.8, NULL),
('Pizza Kümmel', 'Comino, queso y speck', 'Grande', 14, NULL),
('Pizza Oliven', 'Aceitunas, queso y tomate', 'Mediana', 13.5, NULL),
('Pizza Paprika', 'Pimientos variados, queso y salami', 'Mediana', 14.3, NULL),
('Pizza Butter', 'Mantequilla, queso y hierbas', 'Grande', 13, NULL),
('Pizza Radieschen', 'Rábanos, queso crema y rúcula', 'Grande', 14.6, NULL),
('Pizza Schaf', 'Queso de oveja, tomate y albahaca', 'Mediana', 14.9, NULL),
('Pizza Fisch', 'Pescado blanco, queso y limón', 'Grande', 15.5, NULL),
('Pizza Käsefondue', 'Salsa de queso fundido y pan', 'Grande', 14.2, NULL),
('Pizza Salz', 'Sal gruesa, queso y romero', 'Mediana', 13.8, NULL),
('Pizza Kräuteröl', 'Aceite de hierbas, queso y tomate', 'Grande', 14.4, NULL),
('Pizza Zuckerrüben', 'Remolacha dulce, queso y nueces', 'Mediana', 14.7, NULL),
('Pizza Knobli', 'Ajo fresco, queso y perejil', 'Grande', 13.3, NULL),
('Pizza Schmalz', 'Grasa de cerdo, queso y cebolla', 'Grande', 14.5, NULL),
('Pizza Eintopf', 'Guiso de vegetales, queso y pan', 'Mediana', 14, NULL),
('Pizza Finale', 'Mezcla de todos los ingredientes estrella', 'Mediana', 15, NULL),
('Pizza Extra Käse', 'Extra queso mozzarella y gouda', 'Grande', 14.8, NULL),
('Pizza Meister', 'Pizza del maestro con ingredientes secretos', 'Mediana', 16.5, NULL);