# Generated by Django 4.2 on 2025-05-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_pizza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de la Imagen'),
        ),
    ]
